# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals


EXTENSIONS = {
    '%': {'application', 'x-trash'},
    '323': {'text', 'h323'},
    '3gp': {'video', '3gpp'},
    '7z': {'x-7z-compressed', 'application'},
    'abw': {'application', 'x-abiword'},
    'ai': {'application', 'postscript'},
    'aif': {'x-aiff', 'audio'},
    'aifc': {'x-aiff', 'audio'},
    'aiff': {'x-aiff', 'audio'},
    'alc': {'chemical', 'x-alchemy'},
    'amr': {'audio', 'amr'},
    'anx': {'annodex', 'application'},
    'apinotes': {'text', 'apinotes'},
    'apk': {'application', 'vnd.android.package-archive'},
    'art': {'x-jg', 'image'},
    'asar': {'asar', 'binary'},
    'asc': {'text', 'plain'},
    'asf': {'video', 'x-ms-asf'},
    'asn': {'chemical', 'x-ncbi-asn1-spec'},
    'aso': {'x-ncbi-asn1-binary', 'chemical'},
    'asx': {'video', 'x-ms-asf'},
    'atom': {'application', 'atom+xml'},
    'atomcat': {'application', 'atomcat+xml'},
    'atomsrv': {'application', 'atomserv+xml'},
    'au': {'audio', 'basic'},
    'avi': {'video', 'x-msvideo'},
    'awb': {'audio', 'amr-wb'},
    'axa': {'annodex', 'audio'},
    'axv': {'annodex', 'video'},
    'b': {'chemical', 'x-molconn-z'},
    'bak': {'application', 'x-trash'},
    'bash': {'text', 'bash', 'shell'},
    'bat': {'text', 'batch'},
    'bcpio': {'application', 'x-bcpio'},
    'bib': {'text', 'x-bibtex'},
    'bin': {'application', 'octet-stream'},
    'bmp': {'binary', 'image', 'bitmap'},
    'boo': {'x-boo', 'text'},
    'book': {'x-maker', 'application'},
    'brf': {'text', 'plain'},
    'bsd': {'chemical', 'x-crossfire'},
    'bz2': {'bzip2', 'binary'},
    'c': {'text', 'c'},
    'c++': {'text', 'x-c++src'},
    'c3d': {'chemical', 'x-chem3d'},
    'cab': {'application', 'x-cab'},
    'cac': {'chemical', 'x-cache'},
    'cache': {'chemical', 'x-cache'},
    'cap': {'application', 'cap'},
    'cascii': {'chemical', 'x-cactvs-binary'},
    'cat': {'application', 'vnd.ms-pki.seccat'},
    'cbin': {'chemical', 'x-cactvs-binary'},
    'cbr': {'application', 'x-cbr'},
    'cbz': {'x-cbz', 'application'},
    'cc': {'text', 'c++'},
    'cda': {'application', 'x-cdf'},
    'cdf': {'application', 'x-cdf'},
    'cdr': {'x-coreldraw', 'image'},
    'cdt': {'image', 'x-coreldrawtemplate'},
    'cdx': {'chemical', 'x-cdx'},
    'cdy': {'application', 'vnd.cinderella'},
    'cef': {'x-cxf', 'chemical'},
    'cer': {'chemical', 'x-cerius'},
    'cfg': {'text'},
    'chm': {'chemical', 'x-chemdraw'},
    'chrt': {'application', 'x-kchart'},
    'cif': {'x-cif', 'chemical'},
    'class': {'application', 'java-vm'},
    'cls': {'text', 'x-tex'},
    'cmake': {'text', 'cmake'},
    'cmdf': {'x-cmdf', 'chemical'},
    'cml': {'chemical', 'x-cml'},
    'cnf': {'text'},
    'cod': {'application', 'vnd.rim.cod'},
    'coffee': {'text', 'coffee'},
    'com': {'application', 'x-msdos-program'},
    'conf': {'text'},
    'cpa': {'chemical', 'x-compass'},
    'cpio': {'application', 'x-cpio'},
    'cpp': {'text', 'c++'},
    'cpt': {'x-corelphotopaint', 'image'},
    'cr2': {'image', 'x-canon-cr2'},
    'crl': {'application', 'x-pkcs7-crl'},
    'crt': {'pem', 'text'},
    'crw': {'x-canon-crw', 'image'},
    'cs': {'text', 'c#'},
    'csf': {'chemical', 'x-cache-csf'},
    'csh': {'text', 'x-csh'},
    'csm': {'chemical', 'x-csml'},
    'csml': {'chemical', 'x-csml'},
    'cson': {'text', 'cson'},
    'css': {'css', 'text'},
    'csv': {'text', 'csv'},
    'ctab': {'chemical', 'x-cactvs-binary'},
    'ctx': {'x-ctx', 'chemical'},
    'cu': {'text', 'cuda'},
    'cub': {'chemical', 'x-gaussian-cube'},
    'cxf': {'x-cxf', 'chemical'},
    'cxx': {'text', 'c++'},
    'd': {'text', 'x-dsrc'},
    'dat': {'application', 'x-ns-proxy-autoconfig'},
    'davmount': {'application', 'davmount+xml'},
    'dcr': {'application', 'x-director'},
    'deb': {'application', 'x-debian-package'},
    'def': {'text', 'def'},
    'dif': {'video', 'dv'},
    'diff': {'text', 'x-diff'},
    'dir': {'application', 'x-director'},
    'djv': {'vnd.djvu', 'image'},
    'djvu': {'vnd.djvu', 'image'},
    'dl': {'video', 'dl'},
    'dll': {'application', 'x-msdos-program'},
    'dmg': {'application', 'x-apple-diskimage'},
    'dms': {'application', 'x-dms'},
    'doc': {'application', 'msword'},
    'docx': {'application',
            'vnd.openxmlformats-officedocument.wordprocessingml.document'},
    'dot': {'application', 'msword'},
    'dotx': {'application',
            'vnd.openxmlformats-officedocument.wordprocessingml.template'},
    'dtd': {'dtd', 'text'},
    'dv': {'video', 'dv'},
    'dvi': {'application', 'x-dvi'},
    'dx': {'chemical', 'x-jcamp-dx'},
    'dxr': {'application', 'x-director'},
    'ear': {'jar', 'binary', 'zip'},
    'ejs': {'text', 'ejs'},
    'emb': {'x-embl-dl-nucleotide', 'chemical'},
    'embl': {'x-embl-dl-nucleotide', 'chemical'},
    'eml': {'rfc822', 'message'},
    'ent': {'chemical', 'x-pdb'},
    'eot': {'binary', 'eot'},
    'eps': {'eps', 'binary'},
    'eps2': {'application', 'postscript'},
    'eps3': {'application', 'postscript'},
    'epsf': {'application', 'postscript'},
    'epsi': {'application', 'postscript'},
    'erb': {'text', 'erb'},
    'erf': {'x-epson-erf', 'image'},
    'es': {'application', 'ecmascript'},
    'etx': {'text', 'x-setext'},
    'exe': {'binary'},
    'eyaml': {'text', 'yaml'},
    'ez': {'application', 'andrew-inset'},
    'fb': {'x-maker', 'application'},
    'fbdoc': {'x-maker', 'application'},
    'fch': {'chemical', 'x-gaussian-checkpoint'},
    'fchk': {'chemical', 'x-gaussian-checkpoint'},
    'feature': {'text', 'gherkin'},
    'fig': {'x-xfig', 'application'},
    'fish': {'text', 'fish'},
    'flac': {'audio', 'flac'},
    'fli': {'fli', 'video'},
    'flv': {'x-flv', 'video'},
    'fm': {'x-maker', 'application'},
    'frame': {'x-maker', 'application'},
    'frm': {'x-maker', 'application'},
    'gal': {'chemical', 'x-gaussian-log'},
    'gam': {'chemical', 'x-gamess-input'},
    'gamin': {'chemical', 'x-gamess-input'},
    'gau': {'chemical', 'x-gaussian-input'},
    'gcd': {'text', 'x-pcs-gcd'},
    'gcf': {'application', 'x-graphing-calculator'},
    'gcg': {'chemical', 'x-gcg8-sequence'},
    'gemspec': {'text', 'ruby'},
    'gen': {'chemical', 'x-genbank'},
    'gf': {'application', 'x-tex-gf'},
    'gif': {'binary', 'image', 'gif'},
    'gjc': {'chemical', 'x-gaussian-input'},
    'gjf': {'chemical', 'x-gaussian-input'},
    'gl': {'gl', 'video'},
    'gnumeric': {'x-gnumeric', 'application'},
    'go': {'text', 'go'},
    'gotmpl': {'text', 'gotmpl'},
    'gpt': {'chemical', 'x-mopac-graph'},
    'gpx': {'text', 'xml', 'gpx'},
    'gradle': {'text', 'groovy'},
    'groovy': {'text', 'groovy'},
    'gsf': {'x-font', 'application'},
    'gsm': {'audio', 'x-gsm'},
    'gtar': {'application', 'x-gtar'},
    'gyb': {'text', 'gyb'},
    'gyp': {'text', 'python', 'gyp'},
    'gypi': {'text', 'python', 'gyp'},
    'gz': {'gzip', 'binary'},
    'h': {'text', 'c', 'header', 'c++'},
    'h++': {'text', 'x-c++hdr'},
    'hdf': {'application', 'x-hdf'},
    'hh': {'text', 'x-c++hdr'},
    'hin': {'chemical', 'x-hin'},
    'hpp': {'text', 'header', 'c++'},
    'hqx': {'application', 'mac-binhex40'},
    'hs': {'text', 'x-haskell'},
    'hta': {'application', 'hta'},
    'htc': {'text', 'x-component'},
    'htm': {'html', 'text'},
    'html': {'html', 'text'},
    'hxx': {'text', 'header', 'c++'},
    'ica': {'application', 'x-ica'},
    'ice': {'x-conference', 'x-cooltalk'},
    'icns': {'icns', 'binary'},
    'ico': {'icon', 'binary'},
    'ics': {'text', 'calendar'},
    'icz': {'text', 'calendar'},
    'idl': {'text', 'idl'},
    'ief': {'ief', 'image'},
    'iges': {'iges', 'model'},
    'igs': {'iges', 'model'},
    'iii': {'application', 'x-iphone'},
    'inc': {'inc', 'text'},
    'info': {'x-info', 'application'},
    'ini': {'text', 'ini'},
    'inp': {'chemical', 'x-gamess-input'},
    'ins': {'application', 'x-internet-signup'},
    'iso': {'application', 'x-iso9660-image'},
    'isp': {'application', 'x-internet-signup'},
    'ist': {'chemical', 'x-isostar'},
    'istr': {'chemical', 'x-isostar'},
    'j2': {'text', 'jinja'},
    'jad': {'text', 'vnd.sun.j2me.app-descriptor'},
    'jade': {'text', 'jade'},
    'jam': {'application', 'x-jam'},
    'jar': {'jar', 'binary', 'zip'},
    'java': {'text', 'java'},
    'jdx': {'chemical', 'x-jcamp-dx'},
    'jenkinsfile': {'text', 'groovy'},
    'jinja': {'text', 'jinja'},
    'jinja2': {'text', 'jinja'},
    'jmz': {'application', 'x-jmol'},
    'jng': {'image', 'x-jng'},
    'jnlp': {'application', 'x-java-jnlp-file'},
    'jpe': {'image', 'jpeg'},
    'jpeg': {'binary', 'image', 'jpeg'},
    'jpg': {'binary', 'image', 'jpeg'},
    'js': {'text', 'javascript'},
    'json': {'text', 'json'},
    'jsx': {'text', 'jsx'},
    'kar': {'audio', 'midi'},
    'key': {'pem', 'text'},
    'kil': {'application', 'x-killustrator'},
    'kin': {'chemical', 'x-kinemage'},
    'kml': {'text', 'xml', 'kml'},
    'kmz': {'application', 'vnd.google-earth.kmz'},
    'kpr': {'application', 'x-kpresenter'},
    'kpt': {'application', 'x-kpresenter'},
    'ksp': {'application', 'x-kspread'},
    'kt': {'text', 'kotlin'},
    'kwd': {'application', 'x-kword'},
    'kwt': {'application', 'x-kword'},
    'latex': {'x-latex', 'application'},
    'less': {'text', 'less'},
    'lha': {'x-lha', 'application'},
    'lhs': {'text', 'x-literate-haskell'},
    'lin': {'bbolin', 'application'},
    'lsf': {'x-la-asf', 'video'},
    'lsx': {'x-la-asf', 'video'},
    'ltx': {'text', 'x-tex'},
    'lua': {'lua', 'text'},
    'lyx': {'application', 'x-lyx'},
    'lzh': {'application', 'x-lzh'},
    'lzx': {'application', 'x-lzx'},
    'm': {'text', 'objective-c', 'c'},
    'm3g': {'application', 'm3g'},
    'm3u': {'audio', 'x-mpegurl'},
    'm4a': {'audio', 'mpeg'},
    'maker': {'x-maker', 'application'},
    'man': {'application', 'x-troff-man'},
    'manifest': {'text', 'manifest'},
    'map': {'text', 'map'},
    'markdown': {'markdown', 'text'},
    'mcif': {'x-mmcif', 'chemical'},
    'mcm': {'chemical', 'x-macmolecule'},
    'md': {'markdown', 'text'},
    'mdb': {'application', 'msaccess'},
    'me': {'application', 'x-troff-me'},
    'mesh': {'mesh', 'model'},
    'mib': {'text', 'mib'},
    'mid': {'audio', 'midi'},
    'midi': {'audio', 'midi'},
    'mif': {'#chemical', 'x-mif'},
    'mk': {'text', 'makefile'},
    'mkv': {'video', 'x-matroska'},
    'mm': {'text', 'objective-c++', 'c++'},
    'mmd': {'chemical', 'x-macromodel-input'},
    'mmf': {'application', 'vnd.smaf'},
    'mml': {'text', 'mathml'},
    'mmod': {'chemical', 'x-macromodel-input'},
    'mng': {'video', 'x-mng'},
    'moc': {'text', 'x-moc'},
    'modulemap': {'text', 'modulemap'},
    'mol': {'chemical', 'x-mdl-molfile'},
    'mol2': {'x-mol2', 'chemical'},
    'moo': {'chemical', 'x-mopac-out'},
    'mop': {'chemical', 'x-mopac-input'},
    'mopcrt': {'chemical', 'x-mopac-input'},
    'mov': {'quicktime', 'video'},
    'movie': {'x-sgi-movie', 'video'},
    'mp2': {'audio', 'mpeg'},
    'mp3': {'audio', 'mpeg'},
    'mp4': {'video', 'mp4'},
    'mpc': {'chemical', 'x-mopac-input'},
    'mpe': {'video', 'mpeg'},
    'mpeg': {'video', 'mpeg'},
    'mpega': {'audio', 'mpeg'},
    'mpg': {'video', 'mpeg'},
    'mpga': {'audio', 'mpeg'},
    'mpv': {'video', 'x-matroska'},
    'ms': {'application', 'x-troff-ms'},
    'msh': {'mesh', 'model'},
    'msi': {'application', 'x-msi'},
    'mvb': {'chemical', 'x-mopac-vib'},
    'mxf': {'application', 'mxf'},
    'mxu': {'video', 'vnd.mpegurl'},
    'nb': {'application', 'mathematica'},
    'nbp': {'application', 'mathematica'},
    'nc': {'x-netcdf', 'application'},
    'nef': {'image', 'x-nikon-nef'},
    'ngdoc': {'text', 'ngdoc'},
    'nim': {'text', 'nim'},
    'nimble': {'text', 'nimble'},
    'nims': {'text', 'nim'},
    'nwc': {'application', 'x-nwc'},
    'o': {'application', 'x-object'},
    'oda': {'application', 'oda'},
    'oga': {'ogg', 'audio'},
    'ogg': {'ogg', 'audio'},
    'ogv': {'video', 'ogg'},
    'ogx': {'application', 'ogg'},
    'old': {'application', 'x-trash'},
    'orf': {'image', 'x-olympus-orf'},
    'otf': {'otf', 'binary'},
    'oza': {'application', 'x-oz-application'},
    'p': {'text', 'x-pascal'},
    'p12': {'p12', 'binary'},
    'p7r': {'application', 'x-pkcs7-certreqresp'},
    'pac': {'application', 'x-ns-proxy-autoconfig'},
    'pas': {'text', 'x-pascal'},
    'pat': {'x-coreldrawpattern', 'image'},
    'patch': {'text', 'diff'},
    'pbm': {'x-portable-bitmap', 'image'},
    'pcap': {'application', 'cap'},
    'pcf': {'x-font', 'application'},
    'pcf.Z': {'x-font', 'application'},
    'pcx': {'image', 'pcx'},
    'pdb': {'chemical', 'x-pdb'},
    'pdf': {'binary', 'pdf'},
    'pem': {'pem', 'text'},
    'pfa': {'x-font', 'application'},
    'pfb': {'x-font', 'application'},
    'pgm': {'image', 'x-portable-graymap'},
    'pgn': {'application', 'x-chess-pgn'},
    'pgp': {'application', 'pgp-signature'},
    'php': {'text', 'php'},
    'php3': {'application', 'x-httpd-php3'},
    'php3p': {'application', 'x-httpd-php3-preprocessed'},
    'php4': {'text', 'php'},
    'php5': {'text', 'php'},
    'phps': {'x-httpd-php-source', 'application'},
    'pht': {'x-httpd-php', 'application'},
    'phtml': {'text', 'php'},
    'pk': {'application', 'x-tex-pk'},
    'pl': {'text', 'perl'},
    'plantuml': {'text', 'plantuml'},
    'pls': {'x-scpls', 'audio'},
    'pm': {'text', 'x-perl'},
    'png': {'png', 'binary', 'image'},
    'pnm': {'x-portable-anymap', 'image'},
    'po': {'text', 'pofile'},
    'pot': {'text', 'plain'},
    'potx': {'application',
            'vnd.openxmlformats-officedocument.presentationml.template'},
    'pp': {'puppet', 'text'},
    'ppm': {'image', 'x-portable-pixmap'},
    'pps': {'application', 'vnd.ms-powerpoint'},
    'ppsx': {'application',
            'vnd.openxmlformats-officedocument.presentationml.slideshow'},
    'ppt': {'application', 'vnd.ms-powerpoint'},
    'pptx': {'application',
            'vnd.openxmlformats-officedocument.presentationml.presentation'},
    'prf': {'application', 'pics-rules'},
    'proto': {'text', 'proto'},
    'prt': {'chemical', 'x-ncbi-asn1-ascii'},
    'ps': {'application', 'postscript'},
    'psd': {'image', 'x-photoshop'},
    'purs': {'text', 'purescript'},
    'pxd': {'text', 'cython'},
    'pxi': {'text', 'cython'},
    'py': {'text', 'python'},
    'pyc': {'application', 'x-python-code'},
    'pyi': {'text', 'pyi'},
    'pyo': {'application', 'x-python-code'},
    'pyx': {'text', 'cython'},
    'qgs': {'application', 'x-qgis'},
    'qt': {'quicktime', 'video'},
    'qtl': {'application', 'x-quicktimeplayer'},
    'r': {'text', 'r'},
    'ra': {'x-realaudio', 'audio'},
    'ram': {'audio', 'x-pn-realaudio'},
    'rar': {'application', 'rar'},
    'ras': {'x-cmu-raster', 'image'},
    'rb': {'text', 'ruby'},
    'rd': {'chemical', 'x-mdl-rdfile'},
    'rdf': {'application', 'rdf+xml'},
    'rgb': {'x-rgb', 'image'},
    'rhtml': {'application', 'x-httpd-eruby'},
    'rm': {'audio', 'x-pn-realaudio'},
    'roff': {'x-troff', 'application'},
    'ros': {'chemical', 'x-rosdal'},
    'rpm': {'application', 'x-redhat-package-manager'},
    'rs': {'text', 'rust'},
    'rss': {'application', 'rss+xml'},
    'rst': {'text', 'rst'},
    'rtf': {'application', 'rtf'},
    'rtx': {'text', 'richtext'},
    'rxn': {'chemical', 'x-mdl-rxnfile'},
    's': {'text', 'asm'},
    'scala': {'text', 'x-scala'},
    'scr': {'application', 'x-silverlight'},
    'scss': {'text', 'scss'},
    'sct': {'text', 'scriptlet'},
    'sd': {'chemical', 'x-mdl-sdfile'},
    'sd2': {'audio', 'x-sd2'},
    'sdf': {'chemical', 'x-mdl-sdfile'},
    'ser': {'application', 'java-serialized-object'},
    'sgf': {'application', 'x-go-sgf'},
    'sh': {'text', 'shell'},
    'shar': {'application', 'x-shar'},
    'shp': {'application', 'x-qgis'},
    'shtml': {'html', 'text'},
    'shx': {'application', 'x-qgis'},
    'sid': {'prs.sid', 'audio'},
    'sik': {'application', 'x-trash'},
    'silo': {'mesh', 'model'},
    'sis': {'application', 'vnd.symbian.install'},
    'sisx': {'x-epoc', 'x-sisx-app'},
    'sit': {'application', 'x-stuffit'},
    'sitx': {'application', 'x-stuffit'},
    'skd': {'application', 'x-koan'},
    'skm': {'application', 'x-koan'},
    'skp': {'application', 'x-koan'},
    'skt': {'application', 'x-koan'},
    'sls': {'text', 'salt'},
    'smi': {'x-daylight-smiles', '#chemical'},
    'smil': {'application', 'smil'},
    'snd': {'audio', 'basic'},
    'so': {'binary'},
    'spc': {'chemical', 'x-galactic-spc'},
    'spec': {'text', 'spec'},
    'spl': {'application', 'x-futuresplash'},
    'spx': {'ogg', 'audio'},
    'sql': {'text', 'sql'},
    'src': {'application', 'x-wais-source'},
    'stl': {'application', 'vnd.ms-pki.stl'},
    'sty': {'text', 'x-tex'},
    'styl': {'text', 'stylus'},
    'sv4cpio': {'application', 'x-sv4cpio'},
    'sv4crc': {'application', 'x-sv4crc'},
    'svg': {'text', 'svg'},
    'svgz': {'svg+xml', 'image'},
    'sw': {'chemical', 'x-swissprot'},
    'swf': {'binary', 'swf'},
    'swfl': {'application', 'x-shockwave-flash'},
    'swift': {'text', 'swift'},
    'swiftdeps': {'swiftdeps', 'text'},
    't': {'x-troff', 'application'},
    'tac': {'text', 'python', 'twisted'},
    'tar': {'binary', 'tar'},
    'taz': {'application', 'x-gtar'},
    'tcl': {'text', 'x-tcl'},
    'tex': {'text', 'x-tex'},
    'texi': {'application', 'x-texinfo'},
    'texinfo': {'application', 'x-texinfo'},
    'text': {'text', 'plain'},
    'tf': {'text', 'terraform'},
    'tgf': {'x-mdl-tgf', 'chemical'},
    'tgz': {'gzip', 'binary'},
    'thrift': {'text', 'thrift'},
    'tif': {'tiff', 'image'},
    'tiff': {'tiff', 'binary', 'image'},
    'tk': {'text', 'x-tcl'},
    'tm': {'text', 'texmacs'},
    'toml': {'text', 'toml'},
    'torrent': {'application', 'x-bittorrent'},
    'tr': {'x-troff', 'application'},
    'ts': {'text', 'ts'},
    'tsp': {'application', 'dsptype'},
    'tsv': {'text', 'tab-separated-values'},
    'tsx': {'text', 'tsx'},
    'ttf': {'binary', 'ttf'},
    'txt': {'text', 'plain-text'},
    'udeb': {'application', 'x-debian-package'},
    'uls': {'text', 'iuls'},
    'ustar': {'application', 'x-ustar'},
    'val': {'x-ncbi-asn1-binary', 'chemical'},
    'vcd': {'application', 'x-cdlink'},
    'vcf': {'text', 'x-vcard'},
    'vcs': {'text', 'x-vcalendar'},
    'vdx': {'vdx', 'text'},
    'vim': {'text', 'vim'},
    'vmd': {'chemical', 'x-vmd'},
    'vms': {'x-vamas-iso14976', 'chemical'},
    'vrm': {'x-world', 'x-vrml'},
    'vrml': {'x-world', 'x-vrml'},
    'vsd': {'vnd.visio', 'application'},
    'vue': {'text', 'vue'},
    'wad': {'application', 'x-doom'},
    'war': {'jar', 'binary', 'zip'},
    'wasm': {'wasm', 'application'},
    'wav': {'binary', 'wav', 'audio'},
    'wax': {'x-ms-wax', 'audio'},
    'wbmp': {'vnd.wap.wbmp', 'image'},
    'wbxml': {'application', 'vnd.wap.wbxml'},
    'whl': {'binary', 'wheel', 'zip'},
    'wk': {'x-123', 'application'},
    'wkt': {'text', 'wkt'},
    'wm': {'x-ms-wm', 'video'},
    'wma': {'audio', 'x-ms-wma'},
    'wmd': {'x-ms-wmd', 'application'},
    'wml': {'text', 'vnd.wap.wml'},
    'wmlc': {'application', 'vnd.wap.wmlc'},
    'wmls': {'vnd.wap.wmlscript', 'text'},
    'wmlsc': {'application', 'vnd.wap.wmlscriptc'},
    'wmv': {'x-ms-wmv', 'video'},
    'wmx': {'x-ms-wmx', 'video'},
    'wmz': {'application', 'x-ms-wmz'},
    'woff': {'binary', 'woff'},
    'woff2': {'woff2', 'binary'},
    'wp5': {'application', 'vnd.wordperfect5.1'},
    'wpd': {'application', 'vnd.wordperfect'},
    'wrl': {'x-world', 'x-vrml'},
    'wsc': {'text', 'scriptlet'},
    'wsgi': {'wsgi', 'text', 'python'},
    'wvx': {'x-ms-wvx', 'video'},
    'wz': {'application', 'x-wingz'},
    'x3d': {'x3d+xml', 'model'},
    'x3db': {'x3d+binary', 'model'},
    'x3dv': {'model', 'x3d+vrml'},
    'xbm': {'image', 'x-xbitmap'},
    'xcf': {'application', 'x-xcf'},
    'xht': {'application', 'xhtml+xml'},
    'xhtml': {'application', 'xhtml+xml'},
    'xlb': {'application', 'vnd.ms-excel'},
    'xls': {'application', 'vnd.ms-excel'},
    'xlsx': {'application',
            'vnd.openxmlformats-officedocument.spreadsheetml.sheet'},
    'xlt': {'application', 'vnd.ms-excel'},
    'xltx': {'application',
            'vnd.openxmlformats-officedocument.spreadsheetml.template'},
    'xml': {'text', 'xml'},
    'xpi': {'application', 'x-xpinstall'},
    'xpm': {'image', 'x-xpixmap'},
    'xq': {'xquery', 'text'},
    'xql': {'xquery', 'text'},
    'xqm': {'xquery', 'text'},
    'xqu': {'xquery', 'text'},
    'xquery': {'xquery', 'text'},
    'xqy': {'xquery', 'text'},
    'xsd': {'text', 'xml', 'xsd'},
    'xsl': {'text', 'xml', 'xsl'},
    'xspf': {'application', 'xspf+xml'},
    'xtel': {'chemical', 'x-xtel'},
    'xul': {'vnd.mozilla.xul+xml', 'application'},
    'xwd': {'image', 'x-xwindowdump'},
    'xyz': {'chemical', 'x-xyz'},
    'yaml': {'text', 'yaml'},
    'yang': {'text', 'yang'},
    'yin': {'text', 'xml', 'yin'},
    'yml': {'text', 'yaml'},
    'zip': {'binary', 'zip'},
    'zmt': {'chemical', 'x-mopac-input'},
    'zsh': {'text', 'zsh', 'shell'},
    '~': {'application', 'x-trash'}
}
EXTENSIONS_NEED_BINARY_CHECK = {
    'plist': {'plist'},
}

NAMES = {
    '.babelrc': {'text', 'json', 'babelrc'},
    '.bowerrc': {'text', 'json', 'bowerrc'},
    '.coveragerc': {'text', 'ini', 'coveragerc'},
    '.dockerignore': {'text', 'dockerignore'},
    '.editorconfig': {'text', 'editorconfig'},
    '.gitattributes': {'text', 'gitattributes'},
    '.gitignore': {'text', 'gitignore'},
    '.gitmodules': {'text', 'gitmodules'},
    '.jshintrc': {'text', 'json', 'jshintrc'},
    '.mailmap': {'text', 'mailmap'},
    '.mention-bot': {'text', 'json', 'mention-bot'},
    '.npmignore': {'text', 'npmignore'},
    '.yamllint': {'text', 'yaml', 'yamllint'},
    'AUTHORS': EXTENSIONS['txt'],
    'COPYING': EXTENSIONS['txt'],
    'Dockerfile': {'text', 'dockerfile'},
    'Gemfile': EXTENSIONS['rb'],
    'Jenkinsfile': {'text', 'groovy'},
    'LICENSE': EXTENSIONS['txt'],
    'MAINTAINERS': EXTENSIONS['txt'],
    'Makefile': EXTENSIONS['mk'],
    'NOTICE': EXTENSIONS['txt'],
    'PATENTS': EXTENSIONS['txt'],
    'README': EXTENSIONS['txt'],
    'Rakefile': EXTENSIONS['rb'],
    'setup.cfg': EXTENSIONS['ini'],
}
