from __future__ import annotations
INTERPRETERS = {
    'ash': {'shell', 'ash'},
    'awk': {'awk'},
    'bash': {'shell', 'bash'},
    'bats': {'shell', 'bash', 'bats'},
    'cbsd': {'shell', 'cbsd'},
    'csh': {'shell', 'csh'},
    'dash': {'shell', 'dash'},
    'expect': {'expect'},
    'ksh': {'shell', 'ksh'},
    'node': {'javascript'},
    'nodejs': {'javascript'},
    'perl': {'perl'},
    'php': {'php'},
    'php7': {'php', 'php7'},
    'php8': {'php', 'php8'},
    'python': {'python'},
    'python2': {'python', 'python2'},
    'python3': {'python', 'python3'},
    'python2.6': {'python', 'python2', 'python2.6'},
    'python2.7': {'python', 'python2', 'python2.7'},
    'python3.3': {'python', 'python3', 'python3.3'},
    'python3.4': {'python', 'python3', 'python3.4'},
    'python3.5': {'python', 'python3', 'python3.5'},
    'python3.6': {'python', 'python3', 'python3.6'},
    'python3.7': {'python', 'python3', 'python3.7'},
    'python3.8': {'python', 'python3', 'python3.8'},
    'python3.9': {'python', 'python3', 'python3.9'},
    'python3.10': {'python', 'python3', 'python3.10'},
    'python3.11': {'python', 'python3', 'python3.11'},
    'python3.12': {'python', 'python3', 'python3.12'},
    'python3.13': {'python', 'python3', 'python3.13'},
    'ruby': {'ruby'},
    'sed': {'sed'},
    'sh': {'shell', 'sh'},
    'tcsh': {'shell', 'tcsh'},
    'xdotool': {'xdotool'},
    'xonsh': {'shell', 'xonsh'},
    'zsh': {'shell', 'zsh'},
}
